# Form implementation generated from reading ui file 'LoginWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        self.label = QtWidgets.QLabel(parent=Login)
        self.label.setGeometry(QtCore.QRect(70, 40, 71, 16))
        self.label.setObjectName("label")
        self.user_password_input = QtWidgets.QPlainTextEdit(parent=Login)
        self.user_password_input.setGeometry(QtCore.QRect(60, 110, 271, 31))
        self.user_password_input.setObjectName("user_password_input")
        self.label_2 = QtWidgets.QLabel(parent=Login)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.login_button = QtWidgets.QPushButton(parent=Login)
        self.login_button.setGeometry(QtCore.QRect(90, 170, 75, 24))
        self.login_button.setObjectName("login_button")
        self.cancel_button = QtWidgets.QPushButton(parent=Login)
        self.cancel_button.setGeometry(QtCore.QRect(200, 170, 75, 24))
        self.cancel_button.setObjectName("cancel_button")
        self.user_choice = QtWidgets.QComboBox(parent=Login)
        self.user_choice.setGeometry(QtCore.QRect(61, 60, 271, 22))
        self.user_choice.setObjectName("user_choice")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "User"))
        self.label_2.setText(_translate("Login", "Password:"))
        self.login_button.setText(_translate("Login", "Login"))
        self.cancel_button.setText(_translate("Login", "Cancel"))
